version: '2'
services:
  done:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - done_log:/LOG_HOME
    environment:
     spring.datasource.username: DONE
     spring.datasource.password: D0ckEr
     spring.datasource.url: jdbc:mysql://mysql:3306/DONE
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
     - mysql_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D0ckEr
      MYSQL_DATABASE: DONE
      MYSQL_USER: DONE
      MYSQL_PASSWORD: D0ckEr
volumes:
  done_log: {}
  mysql_db: {}